name: network
description: A new Flutter package.
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_annotation: ^4.8.1


dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.3


